### ISSUE TITLE
Allow Specifying Bind Address

### ISSUE THREAD

**Issue by naftulikay** [prkumar/sphinx-reload#5]
As described in #3, I'm running `sphinx-reload` in a Vagrant VM. Since it binds only on the loopback interface, I can't access it from my host machine using Vagrant port forwarding.

Would it be a lot of effort to get it to bind on an arbitrary `--host`?

**Comment by prkumar** [comment]
@naftulikay - Should be pretty straightforward! In fact, I did some snooping and saw that there is an existing fork with this change (plus some other useful improvements): https://github.com/Shir0kamii/sphinx-reload/commit/5e93ad63ed05939fc09e1eb9ab03715bf6b0fff2

I'll open up a PR and see if the author would be willing to contribute the change to the mainline!

**Comment by prkumar** [comment]
@naftulikay - I just released v0.2.0 with the optional `--host` flag. Let me know when you get a chance to try it out, so I know whether I can close this issue as addressed. Thanks!

**Comment by naftulikay** [comment]
@prkumar This absolutely works and it's incredible! Thank you so much!

**Comment by prkumar** [comment]
@naftulikay - Fantastic! Thanks @Shir0kamii for providing the fix 😄
